<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.15">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marty Gale">
<meta name="description" content="Results from 20 seven-point matches between Sage and GNU, including match wins, 4ply review, luck estimates, and selected Sage rollouts.">

<title>Sage vs GNU: Stage 1 – Backgammon Simplified</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../assets/icons/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-71c7b49c685e597d910cb795eccce780.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-8d450d615d30163466618d5f2985fcb2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="icon" type="image/png" href="../../assets/icons/favicon-96x96.png" sizes="96x96">

<link rel="icon" type="image/svg+xml" href="../../assets/icons/favicon.svg">

<link rel="shortcut icon" href="../../assets/icons/favicon.ico">

<link rel="apple-touch-icon" sizes="180x180" href="../../assets/icons/apple-touch-icon.png">

<meta name="apple-mobile-web-app-title" content="BGMS">

<link rel="manifest" href="../../assets/icons/site.webmanifest">


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../assets/bs-shared.css">
<link rel="stylesheet" href="../../assets/bs-components.css">
<link rel="stylesheet" href="../../assets/bs-learn.css">
<link rel="stylesheet" href="../../assets/bs-lesson-analysis.css">
<meta property="og:title" content="Sage vs GNU: Stage 1 – Backgammon Simplified">
<meta property="og:description" content="Results from 20 seven-point matches between Sage and GNU, including match wins, 4ply review, luck estimates, and selected Sage rollouts.">
<meta property="og:site_name" content="Backgammon Simplified">
<meta property="og:image:height" content="630">
<meta property="og:image:width" content="1200">
<meta name="twitter:title" content="Sage vs GNU: Stage 1 – Backgammon Simplified">
<meta name="twitter:description" content="Results from 20 seven-point matches between Sage and GNU, including match wins, 4ply review, luck estimates, and selected Sage rollouts.">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="630">
<meta name="twitter:image-width" content="1200">
<meta name="robots" content="noindex, follow">
<link rel="canonical" href="https://backgammonsimplified.github.io/engine-benchmark/sage-vs-gnu-stage1/index.html">
<meta property="og:url" content="https://backgammonsimplified.github.io/engine-benchmark/sage-vs-gnu-stage1/index.html">
<meta property="og:type" content="article">
<meta property="og:image" content="https://backgammonsimplified.github.io/assets/social/generated/social-sage-vs-gnu-stage1.png">
<meta name="twitter:image" content="https://backgammonsimplified.github.io/assets/social/generated/social-sage-vs-gnu-stage1.png">
<meta name="bs-related-content" content="[&quot;/research/sage-vs-gnu-additional-details.html&quot;]">
<style id="bs-publication-breadcrumb-styles">
.bs-publication-breadcrumbs{margin:.25rem 0 1rem;font-size:.82rem;color:var(--bs-text-muted,#68625a)}
.bs-publication-breadcrumbs ol{display:flex;flex-wrap:wrap;gap:.35rem;list-style:none;margin:0;padding:0}
.bs-publication-breadcrumbs li+li::before{content:"/";margin-right:.35rem;color:var(--bs-border-strong,#bcb4a7)}
.bs-publication-breadcrumbs a{color:inherit;text-underline-offset:.14em}
</style>
<script id="bs-page-publication-jsonld" type="application/ld+json">{"@context":"https://schema.org","@graph":[{"@type":"Report","@id":"https://backgammonsimplified.github.io/engine-benchmark/sage-vs-gnu-stage1/index.html#page","name":"Sage vs GNU: Stage 1","url":"https://backgammonsimplified.github.io/engine-benchmark/sage-vs-gnu-stage1/index.html","isPartOf":{"@type":"WebSite","@id":"https://backgammonsimplified.github.io/#website","name":"Backgammon Simplified","url":"https://backgammonsimplified.github.io/"},"description":"Results from 20 seven-point matches between Sage and GNU, including match wins, 4ply review, luck estimates, and selected Sage rollouts.","headline":"Sage vs GNU: Stage 1","author":{"@type":"Person","name":"Marty Gale","url":"https://backgammonsimplified.github.io/about.html"},"publisher":{"@type":"Organization","name":"Backgammon Simplified","url":"https://backgammonsimplified.github.io/"},"image":"https://backgammonsimplified.github.io/assets/social/generated/social-sage-vs-gnu-stage1.png","breadcrumb":{"@id":"https://backgammonsimplified.github.io/engine-benchmark/sage-vs-gnu-stage1/index.html#breadcrumb"}},{"@type":"BreadcrumbList","@id":"https://backgammonsimplified.github.io/engine-benchmark/sage-vs-gnu-stage1/index.html#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://backgammonsimplified.github.io/"},{"@type":"ListItem","position":2,"name":"Engine Benchmark","item":"https://backgammonsimplified.github.io/engine-benchmark/index.html"},{"@type":"ListItem","position":3,"name":"Sage vs GNU: Stage 1","item":"https://backgammonsimplified.github.io/engine-benchmark/sage-vs-gnu-stage1/index.html"}]}]}</script>
</head>

<body class="nav-fixed bs-editorial-page bs-title-eyebrow bs-engine-benchmark-page quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-xl " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../assets/logo.svg" alt="Backgammon Simplified" class="navbar-logo light-content">
    <img src="../../assets/logo.svg" alt="Backgammon Simplified" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Backgammon Simplified</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../learn/index.html"> 
<span class="menu-text">Learn</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../analyze/index.html"> 
<span class="menu-text">Analyze</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../match-predictor/index.html"> 
<span class="menu-text">Match Predictor</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../engine-benchmark/sage-vs-gnu-stage1/index.html" aria-current="page"> 
<span class="menu-text">Sage vs GNU</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../research/index.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../glossary/index.html"> 
<span class="menu-text">Glossary</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">On this Page</h2>
   
  <ul>
  <li><a href="#at-a-glance" id="toc-at-a-glance" class="nav-link active" data-scroll-target="#at-a-glance">At a glance</a></li>
  <li><a href="#who-won-the-matches" id="toc-who-won-the-matches" class="nav-link" data-scroll-target="#who-won-the-matches">Who won the matches?</a></li>
  <li><a href="#is-gnu-better-than-sage" id="toc-is-gnu-better-than-sage" class="nav-link" data-scroll-target="#is-gnu-better-than-sage">Is GNU Better than Sage?</a></li>
  <li><a href="#did-gnu-have-better-rolls-how-much-did-luck-matter" id="toc-did-gnu-have-better-rolls-how-much-did-luck-matter" class="nav-link" data-scroll-target="#did-gnu-have-better-rolls-how-much-did-luck-matter">Did GNU have better rolls? How much did luck matter?</a></li>
  <li><a href="#why-did-we-choose-gnu-to-review-itself" id="toc-why-did-we-choose-gnu-to-review-itself" class="nav-link" data-scroll-target="#why-did-we-choose-gnu-to-review-itself">Why did we choose GNU to review itself?</a>
  <ul class="collapse">
  <li><a href="#how-did-the-review-rate-the-decisions" id="toc-how-did-the-review-rate-the-decisions" class="nav-link" data-scroll-target="#how-did-the-review-rate-the-decisions">How did the review rate the decisions?</a></li>
  <li><a href="#where-did-the-reviewed-difference-come-from" id="toc-where-did-the-reviewed-difference-come-from" class="nav-link" data-scroll-target="#where-did-the-reviewed-difference-come-from">Where did the reviewed difference come from?</a></li>
  <li><a href="#how-close-were-the-checker-plays" id="toc-how-close-were-the-checker-plays" class="nav-link" data-scroll-target="#how-close-were-the-checker-plays">How close were the checker plays?</a></li>
  <li><a href="#what-about-cube-decisions" id="toc-what-about-cube-decisions" class="nav-link" data-scroll-target="#what-about-cube-decisions">What about cube decisions?</a></li>
  <li><a href="#what-happens-when-sage-and-gnu-disagree-on-the-cube" id="toc-what-happens-when-sage-and-gnu-disagree-on-the-cube" class="nav-link" data-scroll-target="#what-happens-when-sage-and-gnu-disagree-on-the-cube">What happens when Sage and GNU disagree on the cube?</a></li>
  <li><a href="#why-did-the-engines-use-different-ply-depths" id="toc-why-did-the-engines-use-different-ply-depths" class="nav-link" data-scroll-target="#why-did-the-engines-use-different-ply-depths">Why did the engines use different ply depths?</a></li>
  <li><a href="#how-long-did-it-take-to-run" id="toc-how-long-did-it-take-to-run" class="nav-link" data-scroll-target="#how-long-did-it-take-to-run">How long did it take to run?</a></li>
  <li><a href="#how-long-did-the-matches-and-analysis-take" id="toc-how-long-did-the-matches-and-analysis-take" class="nav-link" data-scroll-target="#how-long-did-the-matches-and-analysis-take">How long did the matches and analysis take?</a></li>
  <li><a href="#what-does-this-study-tell-us" id="toc-what-does-this-study-tell-us" class="nav-link" data-scroll-target="#what-does-this-study-tell-us">What does this study tell us?</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<nav class="bs-publication-breadcrumbs" aria-label="Breadcrumb"><ol><li><a href="https://backgammonsimplified.github.io/">Home</a></li><li><a href="https://backgammonsimplified.github.io/engine-benchmark/index.html">Engine Benchmark</a></li><li aria-current="page">Sage vs GNU: Stage 1</li></ol></nav>
<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Sage vs GNU: Stage 1</h1>
<p class="subtitle lead">What happened across 20 seven-point matches?</p>
</div>

<div>
  <div class="description">
    Results from 20 seven-point matches between Sage and GNU, including match wins, 4ply review, luck estimates, and selected Sage rollouts.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Marty Gale </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="bs-editorial-lead">
<p>Sage and GNU played 20 seven-point matches using fixed ply depths and dice files prepared before play. Guess who won?</p>
</div>
<section id="skeptical-of-our-approach-or-results" class="level4 bs-status-panel">
<h4 class="anchored" data-anchor-id="skeptical-of-our-approach-or-results">Skeptical of our approach or results?</h4>
<p>As you read, you may think it was unfair or unscientific, we have a dedicated page for our research method with details. This article summarizes the findings and briefly talks about the methods.</p>
<div class="bs-button-row">
<p><a href="../../research/sage-vs-gnu-additional-details.html" class="bs-button-primary">Read research method details</a></p>
</div>
</section>
<section id="at-a-glance" class="level2">
<h2 class="anchored" data-anchor-id="at-a-glance">At a glance</h2>
<ol type="1">
<li><strong>GNU 13 wins</strong> to <strong>Sage 7 wins</strong>. The binomial test says it is <strong>not statistically significant</strong> result.</li>
<li>4 ply review shows <strong>GNU with lower ER</strong>. Sage’s biggest differences were in Cube decisions.</li>
<li>4 ply review estimated that GNU was luckier, and received the more valuable rolls in every match</li>
<li>TODO Sage’s rollout confirmed is discofirmed the 4 ply review</li>
<li>It took just under 15 mins on avg to run the matches and just under 70 mins to run 4 ply review</li>
</ol>
</section>
<section id="who-won-the-matches" class="level2">
<h2 class="anchored" data-anchor-id="who-won-the-matches">Who won the matches?</h2>
<p>GNU won 13 of the 20 matches. Sage won 7.</p>
</section>
<section id="is-gnu-better-than-sage" class="level2">
<h2 class="anchored" data-anchor-id="is-gnu-better-than-sage">Is GNU Better than Sage?</h2>
<p>Unsure, the test was statisticaly insignificant. We need to run more matches.</p>
<details>
<summary>
What do you mean statistically insignificant? What test did you run?
</summary>
<p>If the engines were equal we would expect a 50% or 10 to 10 result. To judge the statistical significance, we asked a simple question:</p>
<p>If the engines had an equal chance of winning each match, given random chance, how often would we see a 13 to 7 result or better?</p>
<p>Using a two sided binomial test, the answer is about 26% of the time. Statisticians would say the study results show a <strong>p-value of 0.263</strong>. For the result to be significant, we would expect 5% or a p-value of 0.05. Therefore the 13-7 result is statistically insignificant. This does not mean there is a 26% chance that luck caused the result. It means the score, by itself, is not unusual enough to rule out an even matchup.</p>
<p>The TODO <a href="../../research/sage-vs-gnu-additional-details.html#how-strong-was-the-13-7-result">research page</a> explains the test and shows the full distribution. You can also use this <a href="https://www.socscistatistics.com/tests/binomial/calculator/">binomial-test calculator</a> or watch this <a href="https://youtu.be/J8jNoF-K8E8">introduction to the binomial test</a> if you are interested.</p>
</details>
<div class="bs-figure-slot" role="group" aria-label="Match score and twenty-match tile strip placeholder">
<p><span class="bs-figure-slot-label">PENDING VALIDATED FIGURE :: MATCH SCORE AND 20-MATCH TILE STRIP</span></p>
<p>Show GNU with 13 wins and Sage with 7 wins. Add one chronological tile for each public match identifier. Do not use pair labels or A/B labels.</p>
</div>
<!--
figure-id: fig-main-match-wins
expected inputs: public_match_summary.csv, public_match_results.csv
-->
</section>
<section id="did-gnu-have-better-rolls-how-much-did-luck-matter" class="level2">
<h2 class="anchored" data-anchor-id="did-gnu-have-better-rolls-how-much-did-luck-matter">Did GNU have better rolls? How much did luck matter?</h2>
<p>Yes. GNU was luckier according to GNU’s 4-ply review. After adjusting for the rolls, 5 of GNU’s 13 wins no longer clearly showed GNU ahead. This makes the contest look closer than the official 13-7 score.</p>
<details>
<summary>
How was luck measured? And what would the result be after a luck adjustment?
</summary>
<p>The matches were reviewed at 4-ply, but GNU’s luck calculation uses a faster 0-ply evaluation. After each roll, it estimates how much better or worse the player’s position became, assuming the player then makes the best move according to that evaluation.</p>
<p>For a fuller explanation, read the classic article <a href="https://www.bkgm.com/articles/Zare/AMeasureOfLuck.html">A Measure of Luck in Backgammon</a>.</p>
<p>GNU’s review estimated that GNU received the more valuable rolls in all 20 matches. This does not mean the dice were biased or rigged. It means that, according to GNU’s calculation, the rolls improved GNU’s chances more than Sage’s.</p>
<p>The adjustment also estimates whether that roll advantage was large enough to affect which engine appeared ahead. All 7 of Sage’s wins still showed Sage ahead. Of GNU’s 13 wins, 8 still showed GNU ahead, 3 became nearly even, and 2 showed Sage ahead.</p>
<p>This adjustment is an estimate, not a replacement match score.</p>
</details>
<div class="bs-figure-slot" role="group" aria-label="Observed and GNU-adjusted result summary placeholder">
<p><span class="bs-figure-slot-label">PENDING VALIDATED FIGURE :: WHAT CHANGED AFTER GNU’S ROLL ADJUSTMENT</span></p>
<p>Keep the two observed groups separate: the 7 Sage wins all still show Sage ahead; among the 13 GNU wins, 8 still show GNU ahead, 3 become nearly even, and 2 show Sage ahead. Do not combine them under a label such as <strong>winner remained ahead</strong>.</p>
</div>
<!--
figure-id: fig-main-luck-summary
expected inputs: public_match_results.csv or authoritative public luck summary
-->
<div class="bs-inline-note">
<p><span class="bs-technical-label">IMPORTANT LIMITATION</span></p>
<p>We used GNU 4 ply to review the matches and then a Sage rollout to resolve the arguments. GNU 4ply will of course favour GNU’s lower ply decisions.</p>
</div>
</section>
<section id="why-did-we-choose-gnu-to-review-itself" class="level1">
<h1>Why did we choose GNU to review itself?</h1>
<p>GNU has an open source interface with a review tool for match files. We want to open-source the results, so anyone, including yourself to reproduce the result. We can review with other engines in the future, if we can get the developer approval.</p>
<details>
<summary>
How is that fair? Isn’t it biased? What about rollouts?
</summary>
<p>We use GNU 4ply to review the decisions made by both engines. The same review method was used for both sides, which keeps the scoring consistent.</p>
<p>Sage Python Package doesn’t offer a match review function, only evaluate positions. We decided not to implement a match review as it could be error prone. Instead we just replied on GNU 4 ply to evaluate matches, and compare the differences using a Sage rollout.</p>
<p>We ideally would be able to BGBlitz or XG, and will be future work if we can get permission from the developers. This is always a challenge with open-source projects unfortunately. This doesn’t stop you from reviewing the match files we publish in bulk and letting us know what you find! We can publish your results too!</p>
</details>
<section id="want-to-run-your-own-analysis" class="level4 bs-status-panel">
<h4 class="anchored" data-anchor-id="want-to-run-your-own-analysis">Want to run your own analysis?</h4>
<p>Here are the match files, reviewed analysis and data we parsed used for the figures.</p>
<p>TODO</p>
<div class="bs-button-row">
<p><a href="../../research/sage-vs-gnu-additional-details.html" class="bs-button-primary">Read research method details</a></p>
<p><a href="../../engine-benchmark/index.html" class="bs-button-outline">Read about Engine Benchmark</a></p>
<p><a href="https://github.com/backgammonsimplified/backgammon-engine-kit" class="bs-button-outline">Read Github Repo</a></p>
</div>
</section>
<section id="how-did-the-review-rate-the-decisions" class="level2">
<h2 class="anchored" data-anchor-id="how-did-the-review-rate-the-decisions">How did the review rate the decisions?</h2>
<p>GNU had a lower ER. The difference in checker play was smaller, but Sage’s ER is much higher for Cube decisions.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Engine</th>
<th style="text-align: right;">Overall ER</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sage</td>
<td style="text-align: right;">1.416</td>
</tr>
<tr class="even">
<td>GNU</td>
<td style="text-align: right;">0.154</td>
</tr>
</tbody>
</table>
<details>
<summary>
How do you calculate ER?
</summary>
<p>After the matches, GNU compared each eligible checker and cube decision with the “best move”. It then estimated how much <strong>equity</strong> was lost by making the incorrect decision. Equity is the engine’s estimate of how valuable a position or decision is, based on the possible outcomes.</p>
<p>The way to calculate ER (Error Rate) is to take the sum of all equity loss (from the “mistakes”), divides it by the number of all non-forced decisions, and multiplies by 500. This produces the pooled <strong>error rate</strong>, or <strong>ER</strong>. Lower is better. We do not average the ER of the 20 matches. This is the same way <a href="https://bgmastersab.com/">BMAB</a> calculates equity.</p>
<p>The Overall ER is calculated from the combined equity losses and all non-forced decisions. It is not the average of the 20 separate match ER values. A forced decision is for example when you roll while on the bar and not being able to come in, or when you are bearing in, there is only 1 available move. GNU review automatically calculates this, we do not.</p>
<p>In our case:</p>
<p><span class="math display">\[
\text{Sage ER}
=
500 \times \frac{4.735}{1{,}672}
=
1.416
\]</span></p>
<p><span class="math display">\[
\text{GNU ER}
=
500 \times \frac{0.523}{1{,}699}
=
0.154
\]</span></p>
</details>
<div class="bs-figure-slot" role="group" aria-label="Pooled overall ER comparison placeholder">
<p><span class="bs-figure-slot-label">PENDING VALIDATED FIGURE :: POOLED OVERALL ER</span></p>
<p>Show one directly labelled value for each engine, include a visible zero baseline, and state that lower is better. Equity loss and eligible-decision totals may appear as supporting text.</p>
</div>
<!--
figure-id: fig-main-overall-er
expected inputs: public_pooled_performance.csv
-->
</section>
<section id="where-did-the-reviewed-difference-come-from" class="level2">
<h2 class="anchored" data-anchor-id="where-did-the-reviewed-difference-come-from">Where did the reviewed difference come from?</h2>
<p>Most of the gap came from cube decisions.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Decision type</th>
<th style="text-align: right;">Sage ER</th>
<th style="text-align: right;">GNU ER</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Checker play</td>
<td style="text-align: right;">0.291</td>
<td style="text-align: right;">0.177</td>
</tr>
<tr class="even">
<td>Cube decisions</td>
<td style="text-align: right;">9.652</td>
<td style="text-align: right;">0.021</td>
</tr>
</tbody>
</table>
<p>GNU’s review found a relatively small difference in checker play and a much larger difference in cube decisions. Sage’s reviewed cube losses therefore account for most of its overall ER.</p>
<p>This does not prove that every disputed Sage cube decision was wrong. GNU made the judgment, and the separate Sage rollout study examines selected disagreements more deeply.</p>
<div class="bs-figure-slot" role="group" aria-label="Checker and cube pooled ER placeholder">
<p><span class="bs-figure-slot-label">PENDING VALIDATED FIGURE :: CHECKER-PLAY AND CUBE-DECISION ER</span></p>
<p>Use separate panels and separate, clearly labelled scales. Show checker play as Sage 0.291 and GNU 0.177, and cube decisions as Sage 9.652 and GNU 0.021. State that lower is better.</p>
</div>
<!--
figure-id: fig-main-component-er
expected inputs: public_pooled_performance.csv
-->
</section>
<section id="how-close-were-the-checker-plays" class="level2">
<h2 class="anchored" data-anchor-id="how-close-were-the-checker-plays">How close were the checker plays?</h2>
<p>The ER values tell us the total reviewed loss. It also helps to ask how often each played move was very close to GNU’s preferred move.</p>
<p>GNU reports the gap on a normalized equity scale called <strong>EMG</strong>. EMG means equivilent money game, which is how we can compare the equity lost in different match formats. This is called “normalization”. To learn more, you can check out a class article on <a href="https://bkgm.com/articles/Zare/NormalizingErrors/">Normalizing Error</a>.</p>
<p>Even 4 ply analysis doesn’t garuntee the correct move, so we considered if a checker decision was within 0.010 EMG equity of GNU’s preferred play, it to be the “correct” play.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Engine</th>
<th style="text-align: right;">Decisions within 0.010 EMG</th>
<th style="text-align: right;">Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sage</td>
<td style="text-align: right;">1,448 of 1,471</td>
<td style="text-align: right;">98.4%</td>
</tr>
<tr class="even">
<td>GNU</td>
<td style="text-align: right;">1,444 of 1,457</td>
<td style="text-align: right;">99.1%</td>
</tr>
</tbody>
</table>
<p>Both engines were close to 4 ply’s preferred move on the great majority of eligible checker decisions. This is not objective accuracy. It measures closeness to 4ply’s judgment.</p>
<p>A checker decision with zero reviewed loss stays in the total and counts as close. Zero-loss decisions may be left out of a separate plot of non-zero mistakes so the visible errors are easier to compare, but they are not removed from these percentages.</p>
<div class="bs-figure-slot" role="group" aria-label="Checker decision closeness placeholder">
<p><span class="bs-figure-slot-label">PENDING VALIDATED FIGURE :: CHECKER DECISIONS CLOSE TO GNU’S PREFERRED MOVE</span></p>
<p>Title the figure <strong>Checker decisions close to GNU’s preferred move</strong>. Show the percentages and raw counts, define the 0.010 EMG threshold, and avoid the words <strong>correct</strong>, <strong>incorrect</strong>, and <strong>accuracy</strong>.</p>
</div>
<!--
figure-id: fig-main-checker-closeness
expected inputs: public_checker_decision_summary.csv
-->
</section>
<section id="what-about-cube-decisions" class="level2">
<h2 class="anchored" data-anchor-id="what-about-cube-decisions">What about cube decisions?</h2>
<p>Cube decisions need a separate calculation. There are far fewer eligible cube decisions, and routine no-double positions are not all included in the same way.</p>
<p>The final figure uses the same 0.010 equity EMG closeness threshold.</p>
<div class="bs-figure-slot" role="group" aria-label="Cube decision closeness placeholder">
<p><span class="bs-figure-slot-label">PENDING AUDITED FIGURE :: CUBE DECISIONS CLOSE TO GNU’S REVIEW</span></p>
<p>Show the share within 0.010 EMG and the share more than 0.010 EMG away, with percentages, raw counts, and the accepted eligible-decision total. State the zero rule in the subtitle or caption.</p>
</div>
<!--
figure-id: fig-main-cube-closeness
expected inputs: authoritative audited cube-closeness summary derived from public_cube_opportunities.csv
publication gate: audited W2 output required
-->
</section>
<section id="what-happens-when-sage-and-gnu-disagree-on-the-cube" class="level2">
<h2 class="anchored" data-anchor-id="what-happens-when-sage-and-gnu-disagree-on-the-cube">What happens when Sage and GNU disagree on the cube?</h2>
<p>GNU’s review found selected cube decisions where Sage’s original action differed from GNU’s recommendation.</p>
<p>Those positions are being examined with a deeper Sage <strong>rollout</strong>. In a rollout, Sage repeatedly plays forward from the same position to compare how the two actions perform over many continuations. Stage 1 compares only Sage’s original action with GNU’s recommendation. A rollout may support GNU, support Sage’s original action, or remain too close to call.</p>
<div class="bs-status-panel">
<p><span class="bs-status-label">PENDING AUDITED SAGE ROLLOUT RESULTS</span></p>
<p>The public summary will be added after the audited rollout release is available. It will report completed and valid rollouts, results supporting each action, unresolved results, point-estimate-only results, and exclusions.</p>
</div>
<div class="bs-figure-slot" role="group" aria-label="Sage rollout summary placeholder">
<p><span class="bs-figure-slot-label">PENDING FIGURE :: SELECTED SAGE CUBE ROLLOUT RESULTS</span></p>
<p>Use only the audited two-action rollout release. Each published result must link to the position, match context, two actions, rollout settings, paired difference, valid uncertainty range when available, and any exclusion reason.</p>
</div>
<!--
figure-id: fig-main-rollout-summary
publication gate: audited Sage rollout release required
-->
</section>
<section id="why-did-the-engines-use-different-ply-depths" class="level2">
<h2 class="anchored" data-anchor-id="why-did-the-engines-use-different-ply-depths">Why did the engines use different ply depths?</h2>
<p>A <strong>ply</strong> is one layer of lookahead. The engine examines a play, then a reply, then another reply as the ply depth increases.</p>
<p>GNU and Sage label those layers differently. GNU starts at 0-ply, while Sage starts at 1-ply. Giving both engines the same displayed number would therefore give them different amounts of lookahead.</p>
<p>Stage 1 used:</p>
<pre class="text"><code>Checker play
GNU: 3-ply
Sage: 4-ply

Cube decisions
GNU: 2-ply
Sage: 3-ply</code></pre>
<p>For checker play, these were the closest practical fixed-ply depths available in both engines.</p>
<p>For cube decisions, GNU 2-ply and Sage 3-ply both look ahead by both the player on roll and the reply by the opponent. If you use an odd number ply such as 3 ply for GNU, it only considers the player move and not the reply. To simplify, it makes a cube decisions where “riskier” moves are considered better because it isn’t looking for the reply of the opponent.</p>
<p>If that’s confusing, we explain it in detail in our <a href="../../research/sage-vs-gnu-additional-details.html#why-these-ply-depths-were-chosen">research article</a></p>
<p>Matching the amount of lookahead makes the comparison fairer, but it does not make the engines identical. They still use different neural networks, cube models, move filters, and internal methods.</p>
</section>
<section id="how-long-did-it-take-to-run" class="level2">
<h2 class="anchored" data-anchor-id="how-long-did-it-take-to-run">How long did it take to run?</h2>
</section>
<section id="how-long-did-the-matches-and-analysis-take" class="level2">
<h2 class="anchored" data-anchor-id="how-long-did-the-matches-and-analysis-take">How long did the matches and analysis take?</h2>
<p>The live matches were fairly quick and consistent on our setup.</p>
<p>Figure 1</p>
<p>Figure 2</p>
<p>The match times were grouped fairly closely together. In technical terms, they had relatively low variance, meaning there was less difference between the shorter and longer matches.</p>
<p>The 4-ply review times were much more spread out. Although the average was just under 68 minutes, an individual review could take anywhere from just over 32 minutes to almost 2.5 hours. This made the analysis time much less predictable than the match time.</p>
<p>These results are specific our specific hardware and setup. For this pilot, we ran the live matches one at a time to reduce the risk of errors. We ran the 4-ply reviews in parallel, which allowed several completed matches to be analyzed at the same time.</p>
</section>
<section id="what-does-this-study-tell-us" class="level2">
<h2 class="anchored" data-anchor-id="what-does-this-study-tell-us">What does this study tell us?</h2>
<p>In these 20 matches, GNU won more often and received the lower ER under GNU’s own post-match review. Most of the reviewed ER gap came from cube decisions. The checker plays of both engines were very often close to GNU’s preferred move.</p>
<p>GNU’s roll estimates suggest that the official 13-7 score may make the contest look more one-sided than it was. The adjusted result is still an estimate, not a corrected score. The cube-closeness percentage and Sage rollout conclusions also remain pending until their audited releases are ready.</p>
<p>This is evidence about these 20 matches, these engine versions, and these ply depths. It does not establish a permanent ranking between Sage and GNU.</p>
<div class="bs-button-row">
<p><a href="../../research/sage-vs-gnu-additional-details.html" class="bs-button-primary">Read the research details</a></p>
<p><a href="../../engine-benchmark/index.html" class="bs-button-outline">Read about the benchmark tool kit</a></p>
<p><a href="https://github.com/backgammonsimplified/backgammon-engine-benchmark" class="bs-button-outline">View the benchmark repo on Github</a></p>
</div>


</section>
</section>

</main> <!-- /main -->
<script src="../../assets/bs-learn.js" defer=""></script>

<script src="../../assets/bs-lesson-analysis.js" defer=""></script>

<script src="../../assets/bs-learn-scroll.js" defer=""></script>

<script src="../../assets/bs-research-scroll.js" defer=""></script>

<script src="../../assets/bs-glossary.js" defer=""></script>

<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/backgammonsimplified\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2026 Marty Gale - Backgammon Simplified</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../licensing.html">
<p>Code: AGPL-3.0-only · Educational content: CC BY-SA 4.0 · Licensing</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="/updates/index.xml">
<p>RSS</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>